# Generated by Django 5.1.6 on 2025-02-12 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('roll_number', models.IntegerField(unique=True)),
                ('phone_number', models.IntegerField()),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('student_desc', models.TextField(max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.course')),
            ],
        ),
    ]
