# Generated by Django 5.1.6 on 2025-02-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
