# Generated by Django 5.1.6 on 2025-02-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField(unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('student_desc', models.TextField(max_length=300)),
            ],
        ),
    ]
