# Generated by Django 4.2.19 on 2025-02-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_img', models.ImageField(upload_to='uploads/')),
                ('stu_id', models.CharField(default='ID1038951158', max_length=12)),
                ('stu_name', models.CharField(default='NA', max_length=20)),
                ('stu_roll', models.CharField(max_length=10)),
                ('stu_mob', models.BigIntegerField()),
                ('stu_clg_name', models.CharField(max_length=200)),
                ('stu_description', models.TextField()),
            ],
        ),
    ]
