# Generated by Django 5.1.6 on 2025-02-28 03:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author_profile',
            fields=[
                ('author_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_img', models.ImageField(upload_to='author_profile/')),
                ('author_name', models.CharField(max_length=100)),
                ('author_mob', models.CharField(max_length=10, null=True, unique=True)),
                ('author_email', models.CharField(max_length=100, null=True, unique=True)),
                ('author_education', models.CharField(max_length=100, null=True)),
                ('author_books', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.category')),
            ],
        ),
    ]
