# Generated by Django 5.1.6 on 2025-02-28 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('author_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_img', models.ImageField(upload_to='author_profile/')),
                ('author_mob', models.CharField(max_length=10, null=True, unique=True)),
                ('author_email', models.CharField(max_length=100, null=True, unique=True)),
                ('author_education', models.CharField(max_length=100, null=True)),
                ('author_books', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Author_profile',
        ),
    ]
