# Generated by Django 5.1.6 on 2025-03-04 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_authorprofile_delete_author_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='author.category'),
        ),
    ]
